### ISSUE TITLE
Doesn't display any linked css

### ISSUE THREAD

**Issue by smlombardi** [webBoxio/atom-html-preview#1]
atom .089

css files linked do not affect preview.  preview document is plain html.

**Comment by WebMatt83** [comment]
Kwaak's solution isn't working for me. Any suggestions?

**Comment by Ajedi32** [comment]
This doesn't work for me. CSS isn't showing up in Atom, but works fine in Chrome. My link tag is in the html document header and looks like this: `<link rel="stylesheet" href="./assets/css/default.css">`

**Comment by symsmith** [comment]
Works so great, thanks!

**Comment by benen89** [comment]
@kwaak  please explain in more details how to fix the issue, Sorry, I'm a beginner so I didn't get what you exactly should I do to make Atom Preview read css commends as well. really-Really rely on your help
