### ISSUE TITLE
several tabs are displayed

### ISSUE THREAD

**Issue by mattg7** [webBoxio/atom-html-preview#136]
not sure if this is an issue but when I open the preview it opens several identical tabs. I attach a screenshot. Is there a way I can fix this?

![screen shot 2016-11-02 at 2 58 18 pm](https://cloud.githubusercontent.com/assets/23111253/19943233/e6d2d756-a10c-11e6-9940-2f78f01b527a.jpg)

**Comment by Youzhigang** [comment]
Yes,I have the same problem,how should we fix it?

**Comment by kimixu717** [comment]
same!
