### ISSUE TITLE
JS execution

### ISSUE THREAD

**Issue by corporatepiyush** [webBoxio/atom-html-preview#28]
I was using this plugin to develop html page which includes JS code.

the moment  i type 'for' loop

for(var y=0; y < 100)

.... it hangs

as it seems obvious, this plugin tries to refresh html page as there are changes made,it tries to execute for loop and it goes into infinite loop.

can we alt least provide an option to refresh the preview only when file get Saved (Ctrl + S) ?

**Comment by RMKD** [comment]
+1 on execute javascript on save option. I love this package for d3 development! But if i'm loading data or setting up animations it'd be nice to toggle live-update and update-on-save.
