### ISSUE TITLE
preview refresh option

### ISSUE THREAD

**Issue by pearsonca** [webBoxio/atom-html-preview#4]
I often do minor tweaks to css, which basically leads to me to close and then reopen the preview to do updates.

I understand the figuring out how to watch for those kind of updates and reload based on that would be tricky, but a keystroke for refreshing the preview would basically cover my wants.

**Comment by benbac20** [comment]
Would like to have the refresh or reload option available in the HTML preview 
Nice also to have this option available with a shortcut (e.g. F5 or CTRL+R)
