### ISSUE TITLE
Doesn't reload when external CSS modified

### ISSUE THREAD

**Issue by jsncrdnl** [webBoxio/atom-html-preview#49]
I'm running live preview for an HTML page with a linked css file.
The css is linked from "assets/css/main.css" in my project folder where HTML is at the root of my folder.
It's working fine for live preview but if I modify anything in the CSS file, changes aren't reloaded to the live preview unless I close and re-open it for my HTML document.
Couldn't it watch for changes in referenced files and reload preview with changes if detected ?
In the case of css changes, it could only refresh the styles without fully reloading the page (just as Brackets is doing for its live preview)

**Comment by vection** [comment]
+1

**Comment by nasifmdtanjim** [comment]
It doesn't need to be closed and re-opened. Just press `Ctrl`+`s` on the html page and it will reload.

**Comment by 4lphadog** [comment]
i try Ctrl + s (which is the keyboard shortcut for save) and it still doesnt upload the css. i have to close the preview and open it again. its not too much of a hassle but it definitely disrupts my workflow

**Comment by cmanciecko** [comment]
How does the preview know when to refresh?  Could a line of code be added to have the preview refresh any time any open document is changed?

**Comment by jplatte** [comment]
+1

This doesn't only apply to CSS, but to all external resources AFAICT.

**Comment by artaeun** [comment]
+1

**Comment by TsubasaK111** [comment]
+ 1, all external resources.

**Comment by danielroehrig** [comment]
+1
