### ISSUE TITLE
Failure to load in Atom 0.206 due to deprecation 

### ISSUE THREAD

**Issue by nbigaouette** [webBoxio/atom-html-preview#51]
This package cannot be used with Atom >=0.206 due to the deprecation of API.

Not sure how to get which API calls needs to be changed though.

**Comment by impinball** [comment]
Here's the weird part: Deprecation Cop shows nothing (I ran Atom with `--include-deprecated-calls`). I'm about to file a bug on Deprecation Cop itself.

**Comment by impinball** [comment]
Well, apparently, here's the deprecation that atom/deprecation-cop#52 actually found (it's not on a usual code path):

> Accessing PaneView via $::view() is deprecated. Use the raw DOM node or underlying model object instead.

[Here's the offending line.](https://github.com/webBoxio/atom-html-preview/blob/master/lib/atom-html-preview-view.coffee#L57)

**Comment by impinball** [comment]
I know little about Atom's APIs, so I can't really help too much.

**Comment by nbigaouette** [comment]
Using 0.1.8 seems to work now. Thanks!
