### ISSUE TITLE
Preview can be resized left but not right.

### ISSUE THREAD

**Issue by bensk** [webBoxio/atom-html-preview#59]
Click and drag on the vertical divider. Resizes left (larger) but not right (bigger).

**Comment by CandyFace** [comment]
Actually you can resize it, it's just very sensitive. You have to move the mouse slowly, else it will just stop.
It's an issue nonetheless.

**Comment by MaxGraey** [comment]
I agree, it is not very a usable. I think this is issuer is due to the fact that the web-preview window capture mouse events while we try resizing.

**Comment by akivajgordon** [comment]
@MaxGraey must be right because resizing works ok if I drag from the tab bar area at the top. As soon as the mouse moves into the web-preview area, resizing is blocked.

**Comment by ScottBeeson** [comment]
You can also drag it all the way past the edge of the window to the right and then back to the left and it will work as expected.  Weird workaround, but workaround nonetheless.
