### ISSUE TITLE
The package should warn that it actually saves the file continuously!

### ISSUE THREAD

**Issue by donlencho** [webBoxio/atom-html-preview#64]
It's not obvious to a new user that what this does is actually a save and refresh, so I suggest either making this clear or either allow the user to control when the file is overwritten with the changes (it could just save the modified file in a temp file and use that one for the preview... maybe, I don't know...).

**Comment by skyscooby** [comment]
+1 (or +100) on this one.. need a temp buffer for sure file or otherwise.. Perhaps your cutting and pasting and accidentally loose a bunch of stuff or temporarily testing something out expecting the ability to revert to the saved file.

**Comment by Grimeh** [comment]
This should be resolved now. 
@skyscooby, @donlencho can you confirm that you no longer have this problem?

**Comment by skyscooby** [comment]
Confirmed fixed.

**Comment by Jir4** [comment]
Maybe it should be close ?

**Comment by donlencho** [comment]
Right, I had no time to test it again, but if it's fixed, I'm closing it, sorry for the delay.
And thanks for the fix!
