### ISSUE TITLE
Resizing Preview Tab

### ISSUE THREAD

**Issue by stockbrot** [webBoxio/atom-html-preview#65]
When I try to resize the preview tab to a smaller size, it only works when I move the mouse very very slowly.
I'm running on Windows 10, custom Atom theme "atom-material"

**Comment by mattblang** [comment]
On `OSX` it will only move to the left to grow, you have to move the mouse outside of the program to the right to shrink.

**Comment by HYR** [comment]
I'm having the same issue with resizing the preview tab on OS X.

**Comment by szon0111** [comment]
experiencing the same issue on windows 10 as well.

**Comment by h0rsefarm** [comment]
'On OS X the preview tab will only move to the left to grow; you have to move the mouse outside of the program to the right to shrink.'

This is correct.  Grab the window resizer, drag it outside the frame to the right and then you can expand the preview to your desired size.  Pretty annoying when trying to find breakpoints and other tasks.

**Comment by TheSqrtMinus1** [comment]
am also having this problem, on OS X El Capitan


Please fix.
