### ISSUE TITLE
White screen and page not loading

### ISSUE THREAD

**Issue by mintegral** [webBoxio/atom-html-preview#79]
System: Ubuntu 14.04
Atom Version: 1.2.0, 1.2.1, 1.2.2 [edit]
Node version: 5.0.0

Installed atom packages:
* atom-html-preview@0.1.13
* atom-uikit@1.2.0
* linter@1.11.1
* minimap@4.16.0
* project-manager@2.6.5

-------------------------------------------------
Hello,
I get a white screen on the preview window and it doesn't show my page.
When I change the settings to "Trigger on save" the window shows me "Loading HTML Preview…" and that's it. How can I solve this?

Thanks in advance.

EDIT: Downgrading atom-html-preview to version 0.1.11 seems to solve the problem. Thank you jasco.

![index html - -tmp - atom_008](https://cloud.githubusercontent.com/assets/6130083/11154066/582656ea-8a3d-11e5-9476-ff8464912017.png)
![index html - -tmp - atom_010](https://cloud.githubusercontent.com/assets/6130083/11154151/f1641b44-8a3d-11e5-913e-92854fc032b3.png)

**Comment by anoe** [comment]
I have the exact same problem; also using Ubuntu 14.04

**Comment by wlwl2** [comment]
using Ubuntu 14.04 same problem as well

**Comment by metal3d** [comment]
Same on Fedora 22

**Comment by nahush8** [comment]
Same problem on ubuntu 14.04

**Comment by Shaglock** [comment]
Same problem, how to solve that?

**Comment by darkoverlordofdata** [comment]
I started getting this after upgrading to v0.1.13. How do I downgrade a plugin?

**Comment by pshuff** [comment]
Issue also happening on Fedora.

atom-1.2.0-0.1.fc21.x86_64
atom-html-preview:  0.1.13

**Comment by otakucode** [comment]
Getting this as well on Linux Mint 17.2 using atom-1.3.0-beta0.

**Comment by dkatzdev** [comment]
Same on Elementary OS Freya

**Comment by DirkSimons** [comment]
Same here.  Latest Atom (1.2.1) html-preview 0.1.13 running on osx 10.11.1

**Comment by bvj** [comment]
The same. Linux Mint 17.2, Atom 1.2.1, atom-html-preview 0.1.13

**Comment by AbhinavMadahar** [comment]
Same here on Ubuntu 14.04 on ChromeOS with crouton and latest atom-html-preview

**Comment by bvj** [comment]
After Atom update to 1.2.2 still not working

**Comment by jasco** [comment]
Just installed this package for the first time v0.1.13 and encountered this problem.

1. Downgraded the package from the terminal to get working version:

    `apm install atom-html-preview@0.1.11`

2. Restarted atom
3. Closed the *still empty* preview pane and reopened it with ctrl-shift-H to obtain working preview.

I tried 0.1.12.  It appeared to work inconsistently depending on whether I was downgrading or upgrading so I just stayed with 0.1.11.

**Comment by DirkSimons** [comment]
Worked good, thank you jasco.....

**Comment by darkoverlordofdata** [comment]
Reverting to 0.1.11 fixed it... atom seems only as good as it's plugins. I'm becoming underwhelmed.

**Comment by dloret** [comment]
same issue on fedora 23, with html-preview 0.1.13 version.
jasco's workaround works fine, thanks.

**Comment by trojanc** [comment]
Same issues with 0.1.13
Downgrading to 0.1.11 worked
Linux Mint 17.2 x64

**Comment by Kf4btg** [comment]
Had this same issue on Arch x86_64, same solution (downgrading to 0.1.11) fixed it.

Also, since it doesn't appear this has been mentioned yet, I'll add that the console in Atom gave two errors like this when failing to load the preview:

> "Unable to access file:///my-preview-test.html"
> "Not allowed to load local resource file:///my-preview-test.html"

To my untrained eye, it looks like it may be looking for the file on the root of the filesystem? Instead of whatever temporary directory it should be in.  And the second may be some sort of Chrome security warning.  But again, I've very little experience with web development or diagnosing browser issues, so these are pretty much wild guesses on my part.  Nevertheless, I hope this info helps a bit.

**Comment by chenshuiluke** [comment]
Not working on arch linux x64

**Comment by pavdmyt** [comment]
v. 0.1.13 doesn't work, just white screen.
Ubuntu 14.04.3 LTS
Atom 1.3.2

**Comment by atomtm** [comment]
Same here with Debian Jessie. Works with v.0.1.11 though!

**Comment by chromavant** [comment]
downgrading worked for me to on Ubuntu 15.10 `$ apm install atom-html-preview@0.1.11`
