### ISSUE TITLE
Preview not working in LUbuntu

### ISSUE THREAD

**Issue by scottsman22000** [webBoxio/atom-html-preview#81]
I'm running LUbuntu 15.04. Preview does not work with the atom that I downloaded. Which would be the newest .deb release from the website.

**Comment by hzy199411** [comment]
Same as Archlinux.

**Comment by roppert** [comment]
Any hint to a solution?

**Comment by hzy199411** [comment]
@roppert , Thanks. It works well.

**Comment by Grimeh** [comment]
I'm afraid this is my bad, I wasn't able to test my PR in Linux, sorry.
@vedmalex's solution (#83) looks like a good fix, and is how I should have done it in the first place.
