### ISSUE TITLE
some js code does not work 

### ISSUE THREAD

**Issue by YCchou** [webBoxio/atom-html-preview#90]
```javascript
    var text = whichpic.getAttribute("title");
    var description = document.getElementById("description");
    description.childNodes[0].nodeValue = text;
```

this js script doesn't work when i use html preview
could u help me figure out of this?

**Comment by hellfish2** [comment]
did you solve this problem? i have the same error

**Comment by YCchou** [comment]
only thing i remember is i found my code have something wrong...

@hellfish2
