### ISSUE TITLE
Dev tools for html preview

### ISSUE THREAD

**Issue by jordwalke** [webBoxio/atom-html-preview#92]
Are there dev tools for the html preview window? It seems the preview window shares the same dev tools as the Atom editor itself and that means when your code hits a breakpoint, it blocks your entire editor's event loop. I think it should be completely isolated.

**Comment by ZombieHippie** [comment]
This may not be possible for the same reason CodePen, JSFiddle, and JSBin, cannot have completely isolated devtools environments.

Otherwise, we would be looking for a much much more advanced implementation than what the objective of this package is looking at.

**Comment by ZombieHippie** [comment]
I may eat my words: http://electron.atom.io/docs/v0.37.2/api/web-view-tag/#the-webview-tag
