### ISSUE TITLE
atom-html-preview not working

### ISSUE THREAD

**Issue by Skyferia** [webBoxio/atom-html-preview#97]
Please observe here: https://i.gyazo.com/3018bf13a296f08e55c177cf541a9dad.png

**Comment by phillip-haydon** [comment]
Exact same issue here.

**Comment by skmasq** [comment]
I have the same issue right now

**Comment by chromavant** [comment]
Me too.

**Comment by SvartSol** [comment]
same issue here.

**Comment by px200** [comment]
me too

**Comment by Skyferia** [comment]
It worked after reinstalling Atom. Strange.

**Comment by matteocng** [comment]
+1. The pane works if I drag it to the left, but when the code is modified and saved, it becomes blank again. 
v. 0.1.16, Atom 1.4.3, OS X

**Comment by Skyferia** [comment]
@matteocng Try updating Atom to 1.5.4?

**Comment by chromavant** [comment]
I just updated to 1.5.4 but it still won't show a preview on Ubuntu 15.10. I did find a solution here though: https://github.com/webBoxio/atom-html-preview/issues/79. If you're running Ubuntu uninstall the current version of html-preview and run this command in the terminal: `$ apm install atom-html-preview@0.1.11`

**Comment by Skyferia** [comment]
@chromavant Thanks, that is really good to know, it will likely assist after I upgrade my motherboard (and install a distro while maintaining my Win 10).

**Comment by hipo78** [comment]
I'm having the same problem. In order to get the html preview working again, I have to drag the preview window and make it the furthest left tab. This action "fixes" the preview but once the code is modified the html preview breaks again, showing a blank screen. 

Thank you for taking a look.

atom-html-preview: v.0.16; Atom: 1.5.4; Windows 10

**Comment by matteocng** [comment]
@Skyferia I've just updated to 1.5.4 but the issue is still there.
@chromavant Thanks, downgrading the package worked for me.

**Comment by Skyferia** [comment]
@hipo78 You could try doing what chromavant & Matteocng did; they downgraded the package to (I'm guessing)  0.1.11
@matteocng Glad it worked for you. Now I hope [webBoxio] sees this and fixes the bug.

**Comment by vigo** [comment]
hi! just tried with 0.1.13, looks ok to me. please check 0.1.13, if works ok, i'll return to that revision and push the package. unfortunately i'm not able to fix the issue. i called the author yesterday to help us out :) fingers crossed. till the fix, i can revert back to 0.1.13... what do you people think about it?

**Comment by jonny5** [comment]
I just fixed it @vigo. If any if you guys want it to work before the merge, turn the option `triggerOnSave` to true and it should work.

**Comment by Jheysson** [comment]
Open cmd, go to "AppData\Local\atom\bin>" and execute this comand: apm install atom-html-preview@0.1.11

Then open Atom and open your file, press Ctrl + shift + H . It should work

**Comment by sjohn0795** [comment]
> Open cmd, go to "AppData\Local\atom\bin>" and execute this comand: apm install atom-html-preview@0.1.11
> 
> Then open Atom and open your file, press Ctrl + shift + H . It should work

Had the same problem.  This worked for me. Thanks.

**Comment by Shahabkhan99** [comment]
> apm install atom-html-preview@0.1.11

works for me too....Thanks alot
